[project]
name = "koding-dan-kecerdasan-artificial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "pypdf>=6.0.0",
]
